[build]
publish = "public"
command = "hugo --gc --minify --baseURL=$DEPLOY_PRIME_URL"


[context.production.environment]
  HUGO_VERSION = "0.145.0" 
  HUGO_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
